### PR TITLE
Handle failures of load generator

### PR DESCRIPTION
**Pull request by marta-lokhova**
Related to https://github.com/stellar/stellar-core/pull/2220

### CODE REVIEW

**Comment by marta-lokhova** [comment]
somehow i can't assign reviewers for this PR.. either way, @MonsieurNicolas we should probably land this soon, this accommodates new changes in loadgen https://github.com/stellar/stellar-core/pull/2220

**Comment by MonsieurNicolas** [comment]
do we really need this @martalo ? I mean current logic will just cause a timeout if it fails as loadgen never succeeds.
Also, I don't see why we'd retry loadgen itself: if it fails once, I'd rather fail the test

**Comment by marta-lokhova** [comment]
mm, sure, breaking on failure just means we'd fail the test faster (as opposed to waiting for a potentially huge number of retries). So maybe it should just raise if it sees a failure, and not retry load generation?

**Comment by MonsieurNicolas** [comment]
yeah. So my question is do we even bother to "fast fail" as there is already a timeout?

**Comment by marta-lokhova** [comment]
oh i think our timeouts are just too long. If i'm trying to create 1000 accounts, the timeout is 1000*3, so 50 min. Maybe the trick is to just reduce the timeout, e.g. `(numAccountsOrPayments / (batchSize * txRate)) * 2` (double the expected time just in case it takes longer to close ledgers under higher loads), what do you think?

**Comment by MonsieurNicolas** [comment]
Actually, maybe we can't merge this change as is: we use load generator on both old and new builds so the new logic that sets `loadgen.run.failed` won't exist at all.

So yeah I think we need to tune down `num_retries` to something quite a bit smaller like what you suggested.

**Comment by marta-lokhova** [comment]
@MonsieurNicolas the previous change is compatible with old builds, as the commander catches exceptions when accessing metrics. but i agree that we probably don't need it and can rely on retry timeout. either way, i pushed an update (i tripled the expected time instead of doubling to give it more time to recover under high loads)

**Comment by marta-lokhova** [comment]
This is stale now, closing

**Pull request closed without merging**
